config/routes.rb
Rails.application.routes.draw do
  root "projects#show"
  resources :projects do
    resources :lanes
  end
  get 'projects/:id', to: 'projects#show'
  post 'tickets/new', to: 'tickets#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  class_methods do
    def public_count
      all().count
    end
  end
end

app/models/lane.rb
class Lane < ApplicationRecord
    has_many :tickets, dependent: :destroy
    belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
    include Visible
    
    has_many :lanes, dependent: :destroy
end

app/models/ticket.rb
class Ticket < ApplicationRecord
    belongs_to :lane
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lanes_controller.rb
class LanesController < ApplicationController
  def create
    @project = Project.find(params[:project_id])
    @lane = @project.lanes.create(lane_params)
    redirect_to project_path(@project)
  end

  private
    def lane_params
      params.require(:lane).permit(:name)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
    @project = Project.new
  end

  def index
    @projects = Project.all
  end

  def edit
    @project = Project.find(params[:id])
  end

  def show
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      redirect_to @project
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def project_params
      params.require(:project).permit(:name, :description)
    end

  private
    def ticket_params
      params.require(:ticket).permit(:name, :description)
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def new
    @lane = Lane.where("id = ?", params[:ref_models]).first
    @project = Project.find(@lane.project_id)
    @ticket = @lane.tickets.create(ticket_params)
    redirect_to project_path(@project)
  end

  private
    def ticket_params
      params.permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/lanes/_form.html.erb
<%= form_with model: [ @project, @project.lanes.build ] do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/lanes/_lane.html.erb
<li>
    <%= lane.name %>
    <ul>
        <%= render lane.tickets %>
    </ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicketsOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with model: project do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_field :description %><br>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render "form", project: @project %>

app/views/projects/index.html.erb
<h1>Projects</h1>

Total amount of projects: <%= Project.public_count %>

<ul>
  <% @projects.each do |project| %>
    <li>
      <%= link_to project.name, project %>
    </li>
  <% end %>
</ul>

<%= link_to "New Project", new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render "form", project: @project %>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>
<p><%= @project.description %></p>
<%= link_to "Edit Project", edit_project_path %>

<h2>Lanes</h2>
<ul>
<%= render @project.lanes %>
</ul>

<h3>Add a lane:</h3>
<%= render 'lanes/form' %>

<h3>Add a ticket:</h3>
<%= render 'tickets/form' %>

app/views/tickets/_form.html.erb
<%= form_with model: @ticket, url: tickets_new_path, as: "new_ticket" do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :ref_models, "Lane:" %><br>
    <%= form.select :ref_models, options_from_collection_for_select(@project.lanes.all, :id, :name) %>
  </div>

  <div>
    <%= form.submit "Create Ticket" %>
  </div>
<% end %>

app/views/tickets/_ticket.html.erb
<li>
    <%= ticket.name %>,
    <%= ticket.description %>
</li>